# Generated by Django 5.1.4 on 2025-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
