# Generated by Django 5.1.4 on 2025-01-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fooditem_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='discount_price',
            new_name='pre_discount_price',
        ),
    ]
